# Generated by Django 3.2 on 2021-04-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spz', models.CharField(max_length=7)),
                ('znacka_typ', models.CharField(max_length=50)),
                ('pocet_km_najetych', models.IntegerField()),
                ('technicka_kontrola', models.DateField()),
            ],
        ),
    ]
