# Generated by Django 3.2 on 2021-04-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_zakaznik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vypujcka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_vypujcky_zac', models.DateTimeField()),
                ('datum_vypujcky_kon', models.DateTimeField()),
                ('cena_vypujcky', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='zakaznik',
            name='cislo_rp',
            field=models.CharField(max_length=20),
        ),
    ]
